### PR TITLE
Send harbormaster failure on arc patch failure

### LINKED ISSUE #63: Handle base commit not found error
Sometimes, diffs are made against commits which haven't been pushed up to remote yet. The build fails in this case, but no notification of result is made to Harbormaster.
```
[workspace] $ /var/lib/arc/arcanist/bin/arc call-conduit differential.querydiffs ********
Applying patch for differential
[workspace] $ git reset --hard 1a9049ef170d7351ca18ba164bfe8e73bcf4fdcd
fatal: Could not parse object '1a9049ef170d7351ca18ba164bfe8e73bcf4fdcd'.
Got non-zero exit code resetting to base commit 1a9049ef170d7351ca18ba164bfe8e73bcf4fdcd: 128
[workspace] $ git clean -fd -f
[workspace] $ git submodule update --init --recursive
[workspace] $ /var/lib/arc/arcanist/bin/arc patch --nobranch --diff 3955 --nocommit ********


    This diff is against commit 1a9049ef170d7351ca18ba164bfe8e73bcf4fdcd, but
    the commit is nowhere in the working copy. Try to apply it against the
    current working copy state? (cabbdf90274bcef598ae45a47c1ceb0c7ba2b1ec)
    [Y/n] Exception
The program is attempting to read user input, but stdin is being piped from some other source (not a TTY).
(Run with `--trace` for a full exception trace.)
49[arcanist] Error applying arc patch; got non-zero exit code 1
```
The plugin should handle this case and either
* report build failure on Phabricator (Harbormaster)
* allow applying the patch on some git reference (like master branch) through a configuration

### PR DESCRIPTION
**Pull request by sectioneight**
Fixes #63

### CODE REVIEW

**Comment by sectioneight** [comment]
@jjx

**Comment by sectioneight** [comment]
cc @ChaitanyaPramod

File: src/main/java/com/uber/jenkins/phabricator/PhabricatorNotifier.java [hunk 1]
```diff
@@ -156,16 +159,12 @@ public final boolean perform(final AbstractBuild<?, ?> build, final Launcher lau
...
-            try {
-                JSONObject result = diffClient.sendHarbormasterMessage(phid, harbormasterSuccess);
-                if (result.containsKey("error_info") && !(result.get("error_info") instanceof JSONNull)) {
-                    logger.info("harbormaster",
-                            String.format("Error from Harbormaster: %s", result.getString("error_info")));
-                    return false;
-                }
-            } catch (ConduitAPIException e) {
-                logger.info(CONDUIT_TAG, "unable to post to harbormaster");
-                return true;
```
Comment (sectioneight) [inline src/main/java/com/uber/jenkins/phabricator/PhabricatorNotifier.java]: Slight change in semantics. This used to consider the build "successful" in jenkins even if harbormaster wasn't working. I think the new semantics are better.
